name: prompts.chat
title: prompts.chat
subtitle: World's First & Most Famous Prompts Directory

github_pages:
  baseurl: "/awesome-chatgpt-prompts"
  url: "https://xs-flush.github.io"
  branch: "main"

baseurl: "/awesome-chatgpt-prompts"
url: "https://xs-flush.github.io"
